addSbtPlugin("africa.shuwari.sbt" % "sbt-shuwari" % "0.13.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-dynver" % "5.1.0")
addSbtPlugin("com.github.sbt" % "sbt-git" % "2.1.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.10.4")
addSbtPlugin("africa.shuwari.sbt" % "sbt-openjfx" % "0.1.0")
addSbtPlugin("africa.shuwari.sbt" % "sbt-netbeans" % "0.1.1")
